### ISSUE TITLE
emacs fail to init using darkburn

### ISSUE THREAD

**Issue by huahaiy** [gorauskas/darkburn-theme#1]
I am using spacemacs, and it will fail if I enable darkburn them. 

Debugger entered--Lisp error: (void-variable darkburn-green4)
                                                                                                                                      |  (list (quote :background) "#338833" (quote :foreground) darkburn-green4)
                                                                                                                                      |  (list t (list (quote :background) "#338833" (quote :foreground) darkburn-green4))
                                                                                                                                      |  (list (list t (list (quote :background) "#338833" (quote :foreground) darkburn-green4)))
                                                                                                                                      |  (list (quote diff-refine-added) (list (list t (list (quote :background) "#338833" (quote :foreground) darkburn-green4))))
                                                                                                                                      |  (custom-theme-set-faces (quote darkburn) (quote (button ((t (:underline t))))) (list (quote link) (list (list t (cons (quote :foregr$
                                                                                                                                      |  (let ((class (quote ((class color) (min-colors 89)))) (darkburn-fg+1 "#FFFFEF") (darkburn-fg "#DCDCCC") (darkburn-fg-1 "#656555") (d$
                                                                                                                                      |  eval-buffer(#<buffer  *load*-898056> nil "/Users/huahaiy/.emacs.d/elpa/darkburn-theme-20150919.1731/darkburn-theme.el" nil t)  ; Rea$
                                                                                                                                      |  load-with-code-conversion("/Users/huahaiy/.emacs.d/elpa/darkburn-theme-20150919.1731/darkburn-theme.el" "/Users/huahaiy/.emacs.d/elp$
                                                                                                                                      |  require(darkburn-theme nil noerror)
                                                                                                                                      |  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log ($
                                                                                                                                      |  (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-e$
                                                                                                                                      |  (let ((warning-minimum-level :error)) (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//$
                                                                                                                                      |  spacemacs/load-or-install-package(darkburn-theme)
                                                                                                                                      |  (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg))
                                                                                                                                      |  (cond ((or (eq (quote spacemacs-light) theme) (eq (quote spacemacs-dark) theme)) (spacemacs/load-or-install-package (quote spacemacs$
                                                                                                                                      |  (if (memq theme (custom-available-themes)) nil (cond ((or (eq (quote spacemacs-light) theme) (eq (quote spacemacs-dark) theme)) (spa$
                                                                                                                                      |  spacemacs/load-theme(darkburn)
                                                                                                                                      |  (let ((default-theme (car dotspacemacs-themes))) (spacemacs/load-theme default-theme) (setq spacemacs-used-theme-packages (delq nil $
                                                                                                                                      |  spacemacs/init()
                                                                                                                                      |  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-con$
                                                                                                                                      |  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spa$
                                                                                                                                      |  eval-buffer(#<buffer  *load*> nil "/Users/huahaiy/.emacs.d/init.el" nil t)  ; Reading at buffer position 1033
                                                                                                                                      |  load-with-code-conversion("/Users/huahaiy/.emacs.d/init.el" "/Users/huahaiy/.emacs.d/init.el" t t)
                                                                                                                                      |  load("/Users/huahaiy/.emacs.d/init" t t)
                                                                                                                                      |  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314$
                                                                                                                                      |  command-line()
                                                                                                                                      |  normal-top-level()
                                                                                                                                      |

**Comment by gorauskas** [comment]
bug fixed in a015168
